### ISSUE TITLE
meta: Just say no to compiled languages 

### ISSUE THREAD

**Issue by pfalcon** [decomp/decomp#168]
You asked - community answers! From https://github.com/decomp/decompilation#contribution

> Maybe C++ would be a more natural choice for control flow graph generation?

No. Any lowish-level, extra-barrier-to-entry (compilation) language is waste of time (Go too ;-) ).

**Comment by mewmew** [comment]
Hi Paul!

> > Maybe C++ would be a more natural choice for control flow graph generation?
> 
> No. Any lowish-level, extra-barrier-to-entry (compilation) language is waste of time (Go too ;-) ).

One benefit with using isolated decompilation components is that there may exist several implementations of each component. The current components are implemented in Go, mostly because it is the language I feel most confident writing reliable software in. There are always benefits and drawbacks with any given language or category of languages. One benefit with using statically-typed (often compiled) languages is that they may catch bugs (e.g. adding strings and integers) on compile-time rather than run-time. Meanwhile, one benefit with interpreted languages is that they may improve readability and lower the threshold for new contributors. For instance, Python with [llvmpy](http://www.llvmpy.org/) would be an obvious alternative for some of the decompilation components.

I had a lot of fun implementing the original control flow graph generation component in Go, and feel that I've learned a lot from the experience. The Go implementation required less than 300 lines of code (as measured by `cloc`). If you are up for it, I would challenge you to implement the control flow graph generation component in a language of your choice and see how it compares.

May I ask, which language did you have in mind as an alternative to C++ (and Go)? What would be the primary advantages (and disadvantages) of using this language?

Hope to hear from you, and please let me know if you do decide to take on the challenge. I would of cause be happy to help you out if you reach any stumbling blocks!

Cheers /u

**Comment by mewmew** [comment]
Cool, I just noticed your [graph-llvm-ir](https://github.com/pfalcon/graph-llvm-ir) repo! Seems like the challenge won't be too challenging for you, so I'll try to think of a way to make it more interesting :)

**Comment by pfalcon** [comment]
> Cool, I just noticed your graph-llvm-ir repo!

Not only that, I have https://github.com/pfalcon/llvm-codegen-py . Just as you predict, using Python and llvmpy was an obvious choice. Along the way, I figured that LLVM is just a heavy dependency which can be got rid of (while sticking to LLVM IR syntax). If by "control flow graph generation" you mean parsing flat representation into basic block and CFG objects, then implementation for basic subset of LLVM IR is 221 physical lines in Python: https://github.com/pfalcon/llvm-codegen-py/blob/master/parse.py .

While LLVM IR is important in establishing a common standard for IR (that's how it differs from bunch of other academic projects which are now dead and forgotten), it's also over-engineered for many usages. My latest "control flow graph generation" from a real-world RISC assembly takes 110 Python lines.

But I don't find all the above fun. Well, ok, maybe it was fun for me. But now seeing you and bunch other people having the same "fun", all I see is **great** waste of effort. We're drowned in trivialities like "control flow graph generation" and never can reach "stumbling blocks" aka really interesting, challenging stuff.

Moreover, we make artificial barriers among our works by using various funky languages, so can't reuse each other's work (the best answer to this passage would be elaborating what you mean by "isolated decompilation components" - do they communicate with each other using a human-readable external representation? If so, it's already a win which some people "can't get": https://github.com/EiNSTeiN-/decompiler/issues/9 , but even if so, it's a start of new round of issues, like the guy in that ticket points out: "As I mentioned it will lose tons of information", devising and maintaining external representation for all types of info is a work on its own).

> What would be the primary advantages (and disadvantages) of using this language?

So, let me pimp up my random language, which is of course Python per above. It's strictly typed language, while being dynamically typed. That means that passing a string where number is expected or even passing float where int is expected (like indexing a list) will lead to error, so there won't be unexpected or undefined behavior. The errors are runtime, yes. Statically typed languages can catch some errors at compile-time, yeah. But let's face it - the most errors are runtime, higher-semantic-level anyway, so anyway there should be tests, be it statically-typed or dynamically typed language.

Go is a language to write "reliable software", which doesn't have exception handling. So, it's gotta be a language "to write reliable software which puts burden on a user". Perhaps, it's useful for writing heart stimulators? No, because it's garbage-collected so not suitable for critical/real-time systems. But the biggest of Go is Google. Google is a media company which makes money by generating buzz. After that, projects are shamelessly killed. This year they kill GoogleCode, and the rumors say that Go has already generated all the buzz it could, so it scheduler for slaughter next year. You may respond that Go is open-source project and can live without Google, but then open-source community can not to swallow that lure at all and use languages with longer and independent history and free from "exciting new" paradigms like "exception handling is hard to optimize, so instead of trying hard to optimize it, let's just throw it away".

> Hope to hear from you, and please let me know if you do decide to take on the challenge.

That makes me think - when I was working on "compiler" part (llvm-codegen-py), I wished I could go and ask someone something. But there're very few compiler projects, and I wondered if there's a mailing list for that (to clarify, not to generic compiler stuff like parsing, which is boring topic, but "codegeneration" part). Now I see that rather more folks working on decompilation stuff, and throwing random ticket on github works. But I still wonder if there would/should be a more centralized place for interested folks to come to. What's the story behind https://decomp.org/ ? Not yet/already not?

Thanks.

**Comment by mewmew** [comment]
> the best answer to this passage would be elaborating what you mean by "isolated decompilation components" - do they communicate with each other using a human-readable external representation?

They do indeed, and the UNIX philosophy sums it up in a much better way than I ever could: _Write programs that do one thing and do it well. Write programs to work together. Write programs to handle text streams, because that is a universal interface._

A couple of extracts from relevant sections of the report have been provided below to further clarify what isolated decompilation components means, how the separation of concerns will be validated, and how this separation may facilitate decompilation workflows.

> ## 1 Introduction
> 
> … This paper explores a compositional approach to decompilation which facilitates abstractions to create a pipeline of self-contained components. Since each component interacts through language-agnostic interfaces (well-defined input and output) they may be written in a variety of programming languages. Furthermore, for each component of the decompilation pipeline there may exist multiple implementations with their respective advantages and limitations. The end user (e.g. malware analyst, security researcher, reverse engineer) may select the components which solves their task most efficiently.
> 
> ## 10.2.1 Design Validation
> 
> The principle of separation of concern has influenced every aspect of the design of the de-
> compilation pipeline and its individual components. …
> 
> Secondly, a key component (e.g. data flow analysis) will be implemented in a separate programming language (e.g. Haskell, Rust, Prolog, …) to validate the language-agnostic aspects of the design. This component would only be able to interact with the rest of the decompilation pipeline, through well-defined input and output (e.g. LLVM IR, JSON, DOT, …), if the other components were implemented correctly.
> 
> ## 10.2.2 Reliability Improvements
> 
> …
> 
> To ensure reliable interoperability between components written in different programming languages, the intermediate representation (i.e. LLVM IR) of the decompilation pipeline must be well-defined. Previous efforts to produce a formal grammar for LLVM IR have only focused on subsets of the language (as mentioned in section 5.1), and no such grammar has been officially endorsed. Producing an official formal specification for LLVM IR would require huge efforts, but it would enable interesting opportunities. For instance, with a formal grammar it would be possible to create a tool which automatically generates grammatically correct LLVM IR assembly which may be used to verify the various implementation of LLVM IR. This approach has been used by the GoSmith tool to generate random, but legal, Go programs which have uncovered 31 bugs in the official Go compiler, 18 bugs in the Gccgo compiler, 5 bugs in the `llgo` compiler, and 3 bugs in the Go language specification [44].

**Comment by mewmew** [comment]
> Now I see that rather more folks working on decompilation stuff, and throwing random ticket on github works. But I still wonder if there would/should be a more centralized place for interested folks to come to.

For now, discussions on the GitHub issue tracker are preferred as they provide a public archive of design ideas, brainstorming, issues and any anything else related to the project. As the number of project contributors grows, other forms of communication will be required. For this purpose a Slack group has been created (https://decomp.slack.com/). Anyone interested may contact me for an invite.

> What's the story behind https://decomp.org/ ? Not yet/already not?

[decomp.org](https://decomp.org/) is simply the project web-site. Anything related to the project for which a web-site/web service/domain name/... is better suited than a Git repo will be using decomp.org. For now, the front-page simply redirects to the [decomp/decompilation](https://github.com/decomp/decompilation) repo, which acts as the current umbrella for the project. The full story behind decomp.org is not yet know, and will hopefully be realized through collaborate efforts between those interested in joining the project.

**Comment by mewmew** [comment]
Closing this meta issue for now. Thanks for sparking the initial discussions @pfalcon.
