### ISSUE TITLE
cmd/restructure: Consider outputing intermediate graph contraction steps as .dot

### ISSUE THREAD

**Issue by pfalcon** [decomp/decomp#170]
[I groked a suggestion to use the tracker in this project as the main tracker for entire project. So, while I posted "logistical" issues, like getting right Go version, to individual trackers, something which affects "decompilation pipeline", I post here, for easier access.]

So, for debugging and understanding, it would be nice if `restructure` could output a .dot file for each subgraph matching/contraction step.

(Btw, idea to use .dot format for all things graph is a smart idea, ack. You probably should explicitly suggest usage of xdot as a viewer in the README.)

**Comment by mewmew** [comment]
> [I groked a suggestion to use the tracker in this project as the main tracker for entire project. So, while I posted "logistical" issues, like getting right Go version, to individual trackers, something which affects "decompilation pipeline", I post here, for easier access.]

Agreed. This is indeed the intention of this repository, as stated by its description (_This repository acts as an umbrella for the decomp.org project._) and readme:

> This repository acts as an umbrella for the decomp.org project, which implements a decompilation pipeline through the composition of independent [decompilation components](https://github.com/decomp). High-level design plans, ideas and random brainstorming about future decompilation stages are discussed in the [issue tracker](https://github.com/decomp/decompilation/issues).

Please let me know if you think this could be further clarified.

> So, for debugging and understanding, it would be nice if restructure could output a .dot file for each subgraph matching/contraction step.

For understanding, you can play around with the `iso` and `merge` tools of the [graphs](https://github.com/decomp/graphs) repo. Furthermore, please have a look at appendix J (Control Flow Analysis Example), which provides a step-by-step example demonstrating how the control flow analysis works.

Iso example usage:

``` shell
$ go get decomp.org/x/graphs/cmd/iso
$ cd $GOPATH/src/decomp.org/x/graphs/testdata
$ iso list.dot c4_graphs/stmt.dot
Isomorphism of "list" found at node "101":
   "A"="101"
   "B"="105"
Isomorphism of "list" found at node "13":
   "A"="13"
   "B"="17"
Isomorphism of "list" found at node "44":
   "A"="44"
   "B"="48"
Isomorphism of "list" found at node "51":
   "A"="51"
   "B"="55"
Isomorphism of "list" found at node "6":
   "A"="6"
   "B"="10"
Isomorphism of "list" found at node "80":
   "A"="80"
   "B"="84"
$ iso if.dot c4_graphs/stmt.dot
Isomorphism of "if" found at node "17":
   "A"="17"
   "B"="24"
   "C"="32"
Isomorphism of "if" found at node "71":
   "A"="71"
   "B"="74"
   "C"="75"
```

Merge example usage:

``` shell
$ go get decomp.org/x/graphs/cmd/merge
$ cd $GOPATH/src/decomp.org/x/graphs/testdata
$ merge -img pre_loop.dot c4_graphs/stmt.dot
Isomorphism of "pre_loop" found at node "89":
   "A"="89"
   "B"="92"
   "C"="93"
2015/05/25 03:15:34 Creating: "out.dot"
2015/05/25 03:15:34 Creating: "out.png"
$ merge -img list.dot out.dotIsomorphism of "list" found at node "101":
   "A"="101"
   "B"="105"
Isomorphism of "list" found at node "13":
   "A"="13"
   "B"="17"
Isomorphism of "list" found at node "44":
   "A"="44"
   "B"="48"
Isomorphism of "list" found at node "51":
   "A"="51"
   "B"="55"
Isomorphism of "list" found at node "6":
   "A"="6"
   "B"="10"
Isomorphism of "list" found at node "80":
   "A"="80"
   "B"="84"
Isomorphism of "list" found at node "88":
   "A"="88"
   "B"="pre_loop0"
2015/05/25 03:15:45 Creating: "out.dot"
2015/05/25 03:15:45 Creating: "out.png"
$ merge -img if.dot out.dot
Isomorphism of "if" found at node "71":
   "A"="71"
   "B"="74"
   "C"="75"
Isomorphism of "if" found at node "list1":
   "A"="list1"
   "B"="24"
   "C"="32"
2015/05/25 03:15:49 Creating: "out.dot"
2015/05/25 03:15:49 Creating: "out.png"
$ merge -img if_return.dot out.dot
Isomorphism of "if_return" found at node "3":
   "A"="3"
   "B"="7"
   "C"="list4"
Isomorphism of "if_return" found at node "39":
   "A"="39"
   "B"="45"
   "C"="list2"
Isomorphism of "if_return" found at node "98":
   "A"="98"
   "B"="102"
   "C"="list0"
Isomorphism of "if_return" found at node "if0":
   "A"="if0"
   "B"="81"
   "C"="list5"
Isomorphism of "if_return" found at node "if_return0":
   "A"="if_return0"
   "B"="14"
   "C"="if1"
Isomorphism of "if_return" found at node "if_return1":
   "A"="if_return1"
   "B"="52"
   "C"="list3"
2015/05/25 03:15:53 Creating: "out.dot"
2015/05/25 03:15:53 Creating: "out.png"
$ merge -img if_else.dot out.dotIsomorphism of "if_else" found at node "94":
   "A"="94"
   "B"="97"
   "C"="if_return2"
   "D"="106"
Isomorphism of "if_else" found at node "85":
   "A"="85"
   "B"="if_else0"
   "C"="list6"
   "D"="107"
Isomorphism of "if_else" found at node "68":
   "A"="68"
   "B"="if_else1"
   "C"="if_return3"
   "D"="108"
Isomorphism of "if_else" found at node "36":
   "A"="36"
   "B"="if_else0"
   "C"="if_return0"
   "D"="109"
Isomorphism of "if_else" found at node "0":
   "A"="0"
   "B"="if_else1"
   "C"="if_return4"
   "D"="110"
2015/05/25 03:16:03 Creating: "out.dot"
2015/05/25 03:16:03 Creating: "out.png"
```

> Btw, idea to use .dot format for all things graph is a smart idea, ack. You probably should explicitly suggest usage of xdot as a viewer in the README.

Thanks!! I was very happy when I came up with the idea, while visiting Brussels during FOSDEM earlier this year :) This part of the project's history has been recorded in section 7.2 (LLVM IR Library), an extract of which is presented below:

> After months of development it had become clear that the task of implementing libraries
> for LLVM IR was way more time consuming than initially anticipated. The project time
> constrains forced the re-evaluation of using the Go bindings for LLVM, which gave rise
> to a seemingly small but hugely influential idea. The control flow analysis stage should
> operate entirely on graph data structures, thus making it unaware of LLVM IR. This
> idea effectively mitigated the risk of being influenced by the API of the Go bindings for
> LLVM, and gave rise to the data-driven design of the control flow analysis component, as
> further described in section 6.3.2.

I haven't used `xdot` myself. I normally use `dot -Tpng -o foo.png foo.dot`. Please submit a pull request if you'd like, as you have more experience with `xdot` than I.

**Comment by pfalcon** [comment]
> Please let me know if you think this could be further clarified.

Perhaps, if you don't want to get tickets in specific sub-projects, you could disable bug trackers there at all (then maybe add to each README pointer to the main tracker).

> For understanding, you can play around with the iso and merge tools of the graphs repo. Furthermore, please have a look at appendix J (Control Flow Analysis Example), which provides a step-by-step example demonstrating how the control flow analysis works.

Thanks, but I don't want to play with iso/merge tools, and I know how control flow matching works in principle ;-). All I (and most other people) want is to pass an option to `restructure` and have it output a .dot file for each CFG transformation step it makes.

> I haven't used xdot myself. I normally use dot -Tpng -o foo.png foo.dot.

For the possibility of that I mention it. I found it very useful when working with graph, and even hacked a bit during my LLVM hacking (~2 years ago). https://github.com/pfalcon/xdot.py

> Please submit a pull request if you'd like, as you have more experience with xdot than I.

Sorry, I leave such things to you ;-). xdot is included in many big distros, e.g. on debian/ubuntu to install:

```
apt-get install xdot
```

Then `xdot foo.dot`, that's all. Usually, distros ship old(er) version. Main project is here https://github.com/jrfonseca/xdot.py . My fork includes ability to collapse nodes/subgraphs, which is pretty useful when working with big graphs (more info: http://stackoverflow.com/questions/14838820/interactive-graphviz-viewer-with-basic-node-edge-filtering)

**Comment by mewmew** [comment]
> Perhaps, if you don't want to get tickets in specific sub-projects, you could disable bug trackers there at all (then maybe add to each README pointer to the main tracker).

Thanks for the suggestion. For now, having individual issue trackers makes sense, so that specific issues and bugs related to the various components are tracked independently of high-level ideas, and anything affecting the entire decompilation pipeline.

> All I (and most other people) want is to pass an option to restructure and have it output a .dot file for each CFG transformation step it makes.

Point taken. I agree that this would facilitate debugging and give insight into the control flow recovery stage.
