### ISSUE TITLE
cmd/restructure: Better naming for nodes in matching patterns

### ISSUE THREAD

**Issue by pfalcon** [decomp/decomp#171]
```
    {
        "prim": "if",
        "node": "if0",
        "nodes": {
            "A": "F",
            "B": "G",
            "C": "I"
        }
    },
```

doesn't say a human much, sorry. It would rather be:

```
    {
        "prim": "if",
        "node": "if0",
        "nodes": {
            "condition": "F",
            "true_branch": "G",
            "landing_site": "I"
        }
    },
```

(or abbreviated if that's too long).

**Comment by mewmew** [comment]
The `restructure` tool is completely unaware of (or at least should be, otherwise it is a BUG) what the subgraphs represent. It only knows how to locate and merge isomorphisms of subgraphs in graphs. The node names are pulled directly from SUB.dot.

Detailed subgraph example (if_detailed.dot):

``` dot
digraph if {
    condition [label="entry"]
    true_branch
    landing_site [label="exit"]
    condition->true_branch [label="true"]
    condition->landing_site [label="false"]
    true_branch->landing_site
}
```

Iso example using `if_detailed.dot`:

``` shell
$ iso if_detailed.dot c4_graphs/stmt.dot
Isomorphism of "if" found at node "17":
   "condition"="17"
   "landing_site"="32"
   "true_branch"="24"
Isomorphism of "if" found at node "71":
   "condition"="71"
   "landing_site"="75"
   "true_branch"="74"
```

**Comment by pfalcon** [comment]
> The restructure tool is completely unaware of (or at least should be, otherwise it is a BUG) what the subgraphs represent. It only knows how to locate and merge isomorphisms of subgraphs in graphs. The node names are pulled directly from SUB.dot.

... and by propagating logical constraints, we come to conclusion that the way to satisfy the suggestion of this ticket is to put descriptive node names into SUB.dot instead of current A/B/C stuff there ;-).

**Comment by mewmew** [comment]
> ... and by propagating logical constraints, we come to conclusion that the way to satisfy the suggestion of this ticket is to put descriptive node names into SUB.dot instead of current A/B/C stuff there ;-).

The logical constraints have now been propagated :)
